sudo: required
services:
  - docker
before_install:
  - docker build -t junfinent/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run junfinent/react-test npm run test -- --coverage

after_success:
  - docker build -t junfinent/multi-client ./client
  - docker build -t junfinent/multi-nginx ./nginx
  - docker build -t junfinent/multi-server ./server
  - docker build -t junfinent/multi-worker ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push junfinent/multi-client
  - docker push junfinent/multi-nginx
  - docker push junfinent/multi-server
  - docker push junfinent/multi-worker